// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Product.Infrastructure;

#nullable disable

namespace Product.Infrastructure.Migrations.PostgreSql
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002140721_InitialPostgreSql")]
    partial class InitialPostgreSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Product.Domain.Entity.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Address");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Email");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Businesses", (string)null);

                    b.HasDiscriminator<string>("BusinessType").HasValue("Business");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Product.Domain.Entity.Invite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ExpiresAt");

                    b.Property<int?>("InvitedUserId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvitedUserId")
                        .IsUnique();

                    b.HasIndex("SenderId");

                    b.ToTable("Invites", (string)null);
                });

            modelBuilder.Entity("Product.Domain.Entity.OperatorIndustry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("double precision")
                        .HasColumnName("Latitude");

                    b.Property<double>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("double precision")
                        .HasColumnName("Longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("Name");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("Industries", (string)null);
                });

            modelBuilder.Entity("Product.Domain.Entity.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Product.Domain.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("LastName");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea")
                        .HasColumnName("Password");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Username");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("User");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Product.Domain.Entity.VendorFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("RadiusOfWork")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorsFacilities", (string)null);
                });

            modelBuilder.Entity("Product.Domain.Entity.VendorFacilityService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("VendorFacilityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VendorFacilityId");

                    b.ToTable("VendorsFacilityServices", (string)null);
                });

            modelBuilder.Entity("Product.Domain.Entity.Operator", b =>
                {
                    b.HasBaseType("Product.Domain.Entity.Business");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("LogoUrl");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Occupation");

                    b.HasDiscriminator().HasValue("Operator");
                });

            modelBuilder.Entity("Product.Domain.Entity.Vendor", b =>
                {
                    b.HasBaseType("Product.Domain.Entity.Business");

                    b.HasDiscriminator().HasValue("Vendor");
                });

            modelBuilder.Entity("Product.Domain.Entity.Administrator", b =>
                {
                    b.HasBaseType("Product.Domain.Entity.User");

                    b.ToTable("Administrators", (string)null);
                });

            modelBuilder.Entity("Product.Domain.Entity.OperatorUser", b =>
                {
                    b.HasBaseType("Product.Domain.Entity.User");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("integer");

                    b.HasIndex("OperatorId");

                    b.ToTable("OperatorUsers", (string)null);
                });

            modelBuilder.Entity("Product.Domain.Entity.VendorUser", b =>
                {
                    b.HasBaseType("Product.Domain.Entity.User");

                    b.Property<int?>("VendorId")
                        .HasColumnType("integer");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorUsers", (string)null);
                });

            modelBuilder.Entity("Product.Domain.Entity.Invite", b =>
                {
                    b.HasOne("Product.Domain.Entity.User", "InvitedUser")
                        .WithOne("ReceivedInvite")
                        .HasForeignKey("Product.Domain.Entity.Invite", "InvitedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Product.Domain.Entity.User", "Sender")
                        .WithMany("SentInvites")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvitedUser");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Product.Domain.Entity.OperatorIndustry", b =>
                {
                    b.HasOne("Product.Domain.Entity.Operator", "Operator")
                        .WithMany("Industries")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Product.Domain.Entity.RefreshToken", b =>
                {
                    b.HasOne("Product.Domain.Entity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Product.Domain.Entity.User", b =>
                {
                    b.HasOne("Product.Domain.Entity.Business", null)
                        .WithMany("Users")
                        .HasForeignKey("BusinessId");
                });

            modelBuilder.Entity("Product.Domain.Entity.VendorFacility", b =>
                {
                    b.HasOne("Product.Domain.Entity.Vendor", "Vendor")
                        .WithMany("VendorFacilities")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Product.Domain.Entity.VendorFacilityService", b =>
                {
                    b.HasOne("Product.Domain.Entity.VendorFacility", "VendorFacility")
                        .WithMany("Services")
                        .HasForeignKey("VendorFacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VendorFacility");
                });

            modelBuilder.Entity("Product.Domain.Entity.Administrator", b =>
                {
                    b.HasOne("Product.Domain.Entity.User", null)
                        .WithOne()
                        .HasForeignKey("Product.Domain.Entity.Administrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Product.Domain.Entity.OperatorUser", b =>
                {
                    b.HasOne("Product.Domain.Entity.User", null)
                        .WithOne()
                        .HasForeignKey("Product.Domain.Entity.OperatorUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product.Domain.Entity.Operator", "Operator")
                        .WithMany("OperatorUsers")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Product.Domain.Entity.VendorUser", b =>
                {
                    b.HasOne("Product.Domain.Entity.User", null)
                        .WithOne()
                        .HasForeignKey("Product.Domain.Entity.VendorUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product.Domain.Entity.Vendor", "Vendor")
                        .WithMany("VendorUsers")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Product.Domain.Entity.Business", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Product.Domain.Entity.User", b =>
                {
                    b.Navigation("ReceivedInvite");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SentInvites");
                });

            modelBuilder.Entity("Product.Domain.Entity.VendorFacility", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Product.Domain.Entity.Operator", b =>
                {
                    b.Navigation("Industries");

                    b.Navigation("OperatorUsers");
                });

            modelBuilder.Entity("Product.Domain.Entity.Vendor", b =>
                {
                    b.Navigation("VendorFacilities");

                    b.Navigation("VendorUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
