<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>1ab9d955-ef1a-445a-9edb-f56430fa3f6e</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.12" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Product.Application\Product.Application.csproj" />
      <ProjectReference Include="..\Product.Infrastructure\Product.Infrastructure.csproj" />
    </ItemGroup>

</Project>
